anicard/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^$', 'anicard.views.memberCardView', name="card_view"),
    url(r'^request/$', 'anicard.views.cardrequest', name="card_request"),
    url(r'^status/$', 'anicard.views.cardStatus', name="card_status"),
)

anicard/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class MembershipCard(models.Model):
    design = models.ImageField(upload_to="cards/")
    year_start = models.DateField()
    year_end = models.DateField()
    open = models.BooleanField(default=True)

    def __unicode__(self):
        return "Membership: {}-{}".format(self.year_start.year, self.year_end.year)

    def year(self):
        return self.year_start.year


class CardRequest(models.Model):
    user = models.ForeignKey(User)
    year = models.ForeignKey(MembershipCard)
    printed = models.BooleanField(default=False)
    paid = models.BooleanField(default=False)
    delivered = models.BooleanField(default=False)
    lost = models.BooleanField(default=False)

    def name(self):
        return self.user.get_full_name()

    def __unicode__(self):
        return "{}: {}".format(self.name(), self.year.year())

anicard/forms.py
from django import forms


class CardReqForm(forms.Form):
    first_name = forms.CharField(max_length=30, label="Given Name", widget=forms.TextInput(
        attrs={'required': 'required'}))
    last_name = forms.CharField(max_length=30, widget=forms.TextInput(
        attrs={'required': 'required'}), label="Family Name")

anicard/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.views.generic import ListView, DetailView
from anicard.models import MembershipCard, CardRequest
from anicard.forms import CardReqForm
from django.utils import timezone
from django.contrib.auth.decorators import login_required

# Create your views here.

def memberCardView(request):
    card = getCurrentCard()
    if not card:
        return render_to_response('anicard/no-card.html',
            context_instance=RequestContext(request))
    else:
        status = getUsersCard(request.user)
        return render_to_response('anicard/card.html', {'card': card, 'status': status},
            context_instance=RequestContext(request))


def getCurrentCard():
    now = timezone.now()
    options = MembershipCard.objects.filter(open=True, year_start__lte=now, year_end__gte=now)
    if len(options) < 1:
        return None
    else:
        return options[0]

def getUsersCard(usr):
    if usr.is_anonymous():
        return None
    now = timezone.now()
    options = CardRequest.objects.filter(user=usr, year__year_start__lte=now, year__year_end__gte=now)
    if len(options) < 1:
        return None
    else:
        return options.last()

@login_required
def cardrequest(request):
    if getUsersCard(request.user):
        return HttpResponseRedirect('/card/status/')
    card = getCurrentCard()
    if not card:
        return render_to_response('anicard/no-card.html',
            context_instance=RequestContext(request))
    if request.method == 'POST':
        form = CardReqForm(request.POST)
        if form.is_valid():
            request.user.first_name = form.cleaned_data['first_name']
            request.user.last_name = form.cleaned_data['last_name']
            request.user.save()
            req = CardRequest(user=request.user, year=card)
            req.save()
            return HttpResponseRedirect('/card/status/')
        else:
            messages.add_message(request, messages.ERROR, 'Registration error')
            return render_to_response('anicard/request.html', {'form': form},
                context_instance=RequestContext(request))
    else:
        data = {'first_name': request.user.first_name, 'last_name': request.user.last_name}
        form = CardReqForm(data)
        return render_to_response('anicard/request.html', {'form': form},
            context_instance=RequestContext(request))

@login_required
def cardStatus(request):
    card = getUsersCard(request.user)
    if not card:
        return HttpResponseRedirect('/card/request/')
    return render_to_response('anicard/status.html', {'card': card},
            context_instance=RequestContext(request))

anicard/templates/anicard/card.html
{% extends 'base_html.html' %}
{% load static %}
{% load cache %}
{% block titleextra %} - Member's Card{% endblock %}
{% block main %}
<div class="FrontPage">
  <div class="row">
    <div class="col-md-2">
      <dl><dt>Design:</dt><dd><img src="{{card.design.url}}" alt="Card Design" class="img-rounded members-card" ></dd></dl>
    </div>
    <div class="col-md-10">
      <dl class="dl-horizontal">
        <dt>Start date:</dt><dd>{{card.year_start}}</dd>
        <dt>End date:</dt><dd>{{card.year_end}}</dd>
        <dt>Status:</dt>
        <dd>{% if status %}<a href="/card/status/">Check</a>{% else %}<a href="/card/request/">Request</a>{% endif %}</dd>
      </dl>
    </div>
  </div>
</div>
{% endblock %}

{% block extraScripts %}
<script>
var menuItem = document.getElementById("menu_accounts_card");
menuItem.className = "active";
</script>
{% endblock %}

anicard/templates/anicard/no-card.html
{% extends 'base_html.html' %}
{% load static %}
{% load cache %}
{% block titleextra %} - Member's Card{% endblock %}
{% block main %}
<div class="FrontPage">
  <h1>No Card Available</h1>
  <p>Sorry, we don't currently have a card available. Register for our mailing list to be contacted when paid registration is available again.</p>
</div>
{% endblock %}

{% block extraScripts %}
<script>
var menuItem = document.getElementById("menu_accounts_card");
menuItem.className = "active";
</script>
{% endblock %}

anicard/templates/anicard/request.html
{% extends 'base_html.html' %}
{% load static %}
{% load cache %}
{% block titleextra %} - Member's Card - Request{% endblock %}
{% block main %}
<div class="FrontPage">
	<form method="post" class="form-horizontal" action="/card/request/">
		<fieldset>
			<legend>Request a Member's Card</legend>
			<p>Please confirm your name.</p>
			{% csrf_token %}
			<div class="control-group{% if form.first_name.errors %} has-error{% endif %}">
				<label class="control-label" for="id_first_name">{{ form.first_name.label }}</label>
				<div class="controls">
					{{ form.first_name }}
				</div>
				<span class="form-error">{{ form.first_name.errors }}</span>
			</div>
			<div class="control-group{% if form.last_name.errors %} has-error{% endif %}">
				<label class="control-label" for="id_last_name">{{ form.last_name.label }}</label>
				<div class="controls">
					{{ form.last_name }}
				</div>
				<span class="form-error">{{ form.last_name.errors }}</span>
			</div>
			<div class="control-group">
				<div class="controls">
					<button type="submit" class="btn" >Confirm</button>
				</div>
			</div>
		</fieldset>
	</form>  
</div>
{% endblock %}

{% block extraScripts %}
<script>
var menuItem = document.getElementById("menu_accounts_card");
menuItem.className = "active";
</script>
{% endblock %}

anicard/templates/anicard/status.html
{% extends 'base_html.html' %}
{% load static %}
{% load cache %}
{% block titleextra %} - Member's Card Status{% endblock %}
{% block main %}
<div class="FrontPage">
  <div class="row">
    <div class="col-md-2">
      <dl><dt>Design:</dt><dd><img src="{{card.year.design.url}}" alt="Card Design" class="img-rounded members-card" ></dd></dl>
    </div>
    <div class="col-md-10">
      <dl class="dl-horizontal">
        <dt>Start date:</dt><dd>{{card.year.year_start}}</dd>
        <dt>End date:</dt><dd>{{card.year.year_end}}</dd>
        <dt>Name on card:</dt><dd>{{card.name}}</dd>
	<dt>Printed:</dt><dd><span class="glyphicon {% if card.printed %}glyphicon-ok{% else  %}glyphicon-remove{% endif %}" aria-hidden="true"></span></dd>
	<dt>Paid:</dt><dd><span class="glyphicon {% if card.paid %}glyphicon-ok{% else  %}glyphicon-remove{% endif %}" aria-hidden="true"></span></dd>
	<dt>Picked up:</dt><dd><span class="glyphicon {% if card.delivered %}glyphicon-ok{% else  %}glyphicon-remove{% endif %}" aria-hidden="true"></span></dd>
	<dt>Lost:</dt><dd><span class="glyphicon {% if card.lost %}glyphicon-ok{% else  %}glyphicon-remove{% endif %}" aria-hidden="true"></span></dd>
      </dl>
    </div>
  </div>
</div>
{% endblock %}

{% block extraScripts %}
<script>
var menuItem = document.getElementById("menu_accounts_card");
menuItem.className = "active";
</script>
{% endblock %}